version: "3.8"
services:
  app:
    # fase build
    build:
      # context adalah path dari file Dockerfile
      context: .
      dockerfile: Dockerfile
    # nama image hasil build
    image: go-learn-mongodb
    container_name: container-go-learn-mongodb
    # environment yang akan digunakan pada aplikasi
    environment:
      - APP_MONGO_URI=mongodb://root:password@mongodb:27017
      - APP_MONGO_DATABASE_NAME=sample_analytics
      - APP_MONGO_POOL_MIN=10
      - APP_MONGO_POOL_MAX=100
      - APP_MONGO_MAX_IDLE_TIME_SECOND=10
      - APP_MONGO_INIT_CONNECTION_TIME_SECOND=10
      - APP_MONGO_QUERY_TIMEOUT_MS=2000
      - API_TIMEOUT=5
      - DEFAULT_LIMIT=20
    ports:
      - 9999:9999
    restart: always
    depends_on:
      mongodb_db:
        condition: service_healthy
  mongodb_db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=sample_analytics
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb-volume:/data/db
      - mongoconfig:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  mongodb-volume:
  mongoconfig: